# Generated by Django 2.2 on 2019-05-22 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20190522_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hates',
        ),
        migrations.AddField(
            model_name='post',
            name='hates',
            field=models.ManyToManyField(related_name='hated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
